services:
  - type: web
    name: zetaforge-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://zetaforge-universal-app-v2.vercel.app
      - key: MONGODB_URI
        fromDatabase:
          name: zetaforge-mongodb
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: ZETACHAIN_RPC_URL
        value: https://zetachain-athens-evm.blockpi.network/v1/rpc/public
      - key: ZETACHAIN_CHAIN_ID
        value: 7001
      - key: UNIVERSAL_CONTRACT_V2
        value: 0xd306C9a30359EB053F23C92F754206d2fe0Ed93e
      - key: UNIVERSAL_CONTRACT_LEGACY
        value: 0xDE1bE2A2bc97D2B42cDB61812d90214bB2778326
      - key: RATE_LIMIT_WINDOW
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: JWT_SECRET
        sync: false
      - key: CACHE_TTL
        value: 300000
      - key: MAX_RETRIES
        value: 3
      - key: RETRY_DELAY
        value: 1000

databases:
  - name: zetaforge-mongodb
    databaseName: zetaforge
    user: zetaforge_user
